apps/cms/models.py
from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash



class CMSPersmission(object):
    # 255的二进制方式来表示 1111 1111
    ALL_PERMISSION = 0b11111111
    # 1. 访问者权限
    VISITOR =        0b00000001
    # 2. 管理帖子权限
    POSTER =         0b00000010
    # 3. 管理评论的权限
    COMMENTER =      0b00000100
    # 4. 管理板块的权限
    BOARDER =        0b00001000
    # 5. 管理前台用户的权限
    FRONTUSER =      0b00010000
    # 6. 管理后台用户的权限
    CMSUSER =        0b00100000
    # 7. 管理后台管理员的权限
    ADMINER =        0b01000000

cms_role_user = db.Table(
    'cms_role_user',
    db.Column('cms_role_id',db.Integer,db.ForeignKey('cms_role.id'),primary_key=True),
    db.Column('cms_user_id',db.Integer,db.ForeignKey('cms_user.id'),primary_key=True)
)

class CMSRole(db.Model):
    __tablename__ = 'cms_role'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50), nullable=False)
    desc = db.Column(db.String(200),nullable=True)#描述信息
    create_time = db.Column(db.DateTime,default=datetime.now)
    permissions = db.Column(db.Integer,default=CMSPersmission.VISITOR)

    users = db.relationship('CMSUser',secondary=cms_role_user,backref='roles')



class CMSUser(db.Model):
    __tablename__='cms_user'
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    username = db.Column(db.String(50),nullable=False)
    _password = db.Column(db.String(100),nullable=False)
    email = db.Column(db.String(50),nullable=False,unique=True)
    join_time =db.Column(db.DateTime,default=datetime.now)
    """
    想要映射到数据库里面必须添加到manage.py里面
  
    """


    def __init__(self,username,password,email):
        self.username=username
        self.password=password
        self.email=email

    @property
    def password(self):
        return self._password


    @password.setter
    def password(self,raw_password):
        self._password= generate_password_hash(raw_password)

    def check_password(self,raw_password):
        result = check_password_hash(self.password,raw_password)
        #这里也可以写为self._password(代表的是password方法下面的返回值)，其实这里的self.password指的就是这个password方法
        return result
#147讲
    @property
    def permissions(self):
        if not self.roles:
            return 0
        all_permissions = 0
        for role in self.roles:
            permissions = role.permissions
            all_permissions |= permissions
        return all_permissions

    #判断是否有这个权限
    def has_permission(self, permission):
        # all_permissions = self.permissions
        # result = all_permissions&permission == permission
        # return result
        return self.permissions & permission == permission

    @property
    def is_developer(self):
        return self.has_permission(CMSPersmission.ALL_PERMISSION)


#
# user = CMSUser()
# print(user.password)



# 密码：对外的字段名叫做password
# 密码：对内的字段名叫做_password
"""
(my_env) $pwd
/Users/mac/PycharmProjects/bbc
(my_env) $python3 manage.py db migrate
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'cms_role'
INFO  [alembic.autogenerate.compare] Detected added table 'cms_role_user'
  Generating /Users/mac/PycharmProjects/bbc/migrations/versions/725375213f6e_.py
  ...  done
(my_env) $python3 manage.py db upgrade
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 08504da615b9 -> 725375213f6e, empty message
(my_env) $
------------------------------------------------------------------------------
mysql> show databases;
+-----------------------+
| Database              |
+-----------------------+
| information_schema    |
| alembic_demo          |
| flask_alembic_demo    |
| flask_migrate_demo    |
| flask_restful_demo    |
| flask_script_demo     |
| flask_sqlalchemy_demo |
| icbc_demo             |
| mysql                 |
| performance_schema    |
| sys                   |
| zlbbs                 |
+-----------------------+
12 rows in set (0.01 sec)

mysql> use zlbbs;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

mysql> show tables;
+-----------------+
| Tables_in_zlbbs |
+-----------------+
| alembic_version |
| cms_role        |
| cms_role_user   |
| cms_user        |
+-----------------+
4 rows in set (0.00 sec
------------------------------------------------------------------------------

(my_env) $python3 manage.py create_role
(my_env) $

------------------=========================

mysql> select * from cms_role
    -> ;
+----+-----------+---------------------------------------------------+---------------------+-------------+
| id | name      | desc                                              | create_time         | permissions |
+----+-----------+---------------------------------------------------+---------------------+-------------+
|  1 | 访问者    | 只能相关数据，不能修改。                          | 2019-12-23 13:03:42 |           1 |
|  2 | 运营      | 管理帖子，管理评论,管理前台用户。                 | 2019-12-23 13:03:42 |          55 |
|  3 | 管理员    | 拥有本系统所有权限。                              | 2019-12-23 13:03:42 |          63 |
|  4 | 开发者    | 开发人员专用角色。                                | 2019-12-23 13:03:42 |         255 |
+----+-----------+---------------------------------------------------+---------------------+-------------+
4 rows in set (0.00 sec)
"""

apps/cms/forms.py
from wtforms import StringField,IntegerField
from wtforms.validators import Email,InputRequired,Length,EqualTo
from ..forms import BaseForm
from utils import zlcache
from wtforms import ValidationError
from flask import g



class LoginForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确的邮箱格式'),InputRequired(message='请输入邮箱')])
    password = StringField(validators=[Length(6,20,message='请输入正确格式的密码')])
    remember = IntegerField()

class ResetpwdForm(BaseForm):
    oldpwd = StringField(validators=[Length(6,20,message='请输入正确格式的旧密码')])
    newpwd = StringField(validators=[Length(6,20,message='请输入正确格式的新密码')])
    newpwd2 = StringField(validators=[EqualTo("newpwd",message='确认密码必须和新密码保持一致')])



class ResetEmailForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确格式的邮箱！')])
    captcha = StringField(validators=[Length(min=6,max=6,message='请输入正确长度的验证码！')])

    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        captcha_cache = zlcache.get(email)
        if not captcha_cache or captcha.lower() != captcha_cache.lower():
            raise ValidationError('邮箱验证码错误！')

    def validate_email(self, field):
        email = field.data
        user = g.cms_user
        if user.email == email:
            raise ValidationError('不能修改为相同的邮箱！')

apps/cms/__init__.py
from .views import bp
# from .models import  CMSUser
import apps.cms.hooks

apps/cms/views.py
from flask import  Blueprint,views,render_template,request,session,redirect,url_for,g,jsonify
from  .forms import LoginForm,ResetpwdForm,ResetEmailForm
from .models import CMSUser,CMSPersmission
from .decorators import login_required,permission_required
import config
from exts import db,mail
from flask_mail import Message
from utils import restful,zlcache
import string,random

bp = Blueprint("cms",__name__,url_prefix='/cms')

@bp.route('/logout/')
@login_required
def logout():
    del session[config.CMS_USER_ID]
    return redirect(url_for('cms.login'))


@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/cms_profile.html')


@bp.route('/')
@login_required
def index():
    return render_template('cms/cms_index.html')
# render_template('cms/cms_index.html')




"""
>>> import string
>>> string.ascii_letters
'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
>>> list(string.ascii_letters)
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
"""
@bp.route('/email_captcha/')
def email_captcha():
     email=request.args.get('email')
     if not email:
        return  restful.params_error('请传递邮箱参数')

     source = list(string.ascii_letters)
     source.extend(map(lambda x:str(x),range(0,10)))#等效于下面一行
     # source.extend(["0","1","2","3","4","5","6","7","8","9"])
     captcha= "".join(random.sample(source,6))


     #给这个邮箱发送邮件
     message =Message("学习课堂",recipients=[email],body='您的验证码是:%s'%captcha)
     try:
         mail.send(message)
     except:
         return restful.server_error()
     zlcache.set(email, captcha)
     return restful.success()


# @bp.route('/email/')
# def send_email():
#     message = Message('邮件发送',recipients=['596414331@qq.com'],body='这是测试')
#     mail.send(message)
#     return 'success'



"""
登录界面 
"""

@bp.route('/posts/')
@login_required
@permission_required(CMSPersmission.POSTER)
def posts():
    return render_template('cms/cms_posts.html')

@bp.route('/comments/')
@login_required
@permission_required(CMSPersmission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')

@bp.route('/boards/')
@login_required
@permission_required(CMSPersmission.BOARDER)
def boards():
    return render_template('cms/cms_boards.html')

@bp.route('/fusers/')
@login_required
@permission_required(CMSPersmission.FRONTUSER)
def fusers():
    return render_template('cms/cms_fusers.html')

@bp.route('/cusers/')
@login_required
@permission_required(CMSPersmission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')

@bp.route('/croles/')
@login_required
@permission_required(CMSPersmission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')



class LoginView(views.MethodView):
    def get(self,message=None):
        return render_template('cms/cms_login.html',message=message )

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CMSUser.query.filter_by(email = email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID]=user.id
                """
            #session是存储了user_id,同时这个session又保存在cookies当中,当用户再次请求的时候会把cookies提交给服务器
                这时候falsk就会把cookies中的session拿到,而后把相应的数据解码出来
                
                """
                if remember:#如果用户有提交这个remember,那么就让这个cookies信息保存的长一点
                    #如果session.permanent = True
                    #则过期时间31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return self.get(message="邮箱或者密码错误")

        else:
            # print(form.errors)
            # message = form.errors.popitem()[1][0]
            message = form.get_error()
            # print(message)
            # 请输入正确格式的密码

            """
            form.errors.popitem()[1]是一个列表:
         {'password': ['请输入正确格式的密码']}
         里面的第0项为:请输入正确格式的密码

            """

            return self.get(message=message)


class ResetPwdView(views.MethodView):
    decorators=[login_required]
    def get(self):
        return render_template('cms/cms_resetpwd.html')

    def post(self):
        form = ResetpwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user
            if user.check_password(oldpwd):
                user.password = newpwd
                db.session.commit()
                # return jsonify({"code": 200, "message": ""})
                return restful.success()
            else:
                # print("post里层循环400")
                return restful.params_error("旧密码错误")
        else:
            message = form.get_error()
            # print("post外层循环400")
            return restful.params_error(form.get_error())


class ResetEmailView(views.MethodView):
    decorators = [login_required]
    def get(self):
        return render_template('cms/cms_resetemail.html')
    def post(self):
        form = ResetEmailForm(request.form)
        if form.validate():
            email = form.email.data
            g.cms_user.email = email
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(form.get_error())




bp.add_url_rule('/login/',view_func=LoginView.as_view('login'))
##一定要和base.js里面的重置密码url保持一致;这里是和第31行一样
bp.add_url_rule('/resetpwd/',view_func=ResetPwdView.as_view('resetpwd'))
##一定要和base.js里面的重置邮箱url保持一致;这里是和第35行一样
bp.add_url_rule('/resetemail/',view_func=ResetEmailView.as_view('resetemail'))

templates/cms/cms_base.html
{% from "common/_macros.html" import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ static('cms/css/base.css')}}">
    <script src="{{ static('cms/js/base.js')}}"></script>
    <script src="{{ static("common/zlajax.js") }}"></script>

 <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">

    <script src="{{ static("common/sweetalert/sweetalert.min.js")}}"></script>
    <script src="{{ static("common/sweetalert/zlalert.js")}}"></script>
{#上面这三行是为优化密码修改而添加的#}

{% block head %}{% endblock %}
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}</a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>

                   {% set cms_user = g.cms_user %}
                {% if cms_user.has_permission(CMSPermission.POSTER) %}
                    <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.COMMENTER) %}
                    <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>

                {% endif %}
                {% if cms_user.has_permission(CMSPermission.BOARDER) %}
                    <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>

                {% endif %}
                {% if cms_user.has_permission(CMSPermission.FRONTUSER) %}
                    <li class="nav-group user-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>

                {% endif %}
                {% if cms_user.has_permission(CMSPermission.CMSUSER) %}
                    <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>

                {% endif %}
                {% if cms_user.is_developer %}
                    <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>

                {% endif %}
{##}
{#                <li class="nav-group post-manage"><a href="#">帖子管理</a></li>#}
{#                <li class="comments-manage"><a href="#">评论管理</a></li>#}
{#                <li class="board-manage"><a href="#">板块管理</a></li>#}
{##}
{#                <li class="nav-group user-manage"><a href="#">用户管理</a></li>#}
{#                <li class="role-man age"><a href="#">组管理</a></li>#}
{##}
{#                <li class="nav-group cmsuser-manage"><a href="#">CMS用户管理</a></li>#}
{#                <li class="cmsrole-manage"><a href="#">CMS组管理</a></li>#}
            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}
                {% endblock %}

            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}

{% block title %}板块管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是板块管理页面
{% endblock %}

templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}

{% block title %}评论管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是评论管理页面
{% endblock %}

templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}

{% block title %}CMS角色管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是CMS角色管理页面
{% endblock %}

templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}CMS用户管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是CMS用户管理页面
{% endblock %}

templates/cms/cms_fusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}前台用户管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是前台用户管理页面
{% endblock %}

templates/cms/cms_index.html
{% extends 'cms/cms_base.html'%}
{% block title %}
    study课堂CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到study课堂CMS管理系统
{% endblock %}
{#{% block main_content %}#}
{#{% endblock %}#}

templates/cms/cms_index_backup.html
{% from "common/_macros.html" import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>标题</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ static('cms/css/base.css')}}">
    <script src="{{ static('cms/js/base.js ')}}"></script>
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">知了课堂论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">{{ g.cms_user.username }}<span>[超级管理员]</span></a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="#">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="#">个人信息</a></li>
                        <li><a href="#">修改密码</a></li>
                        <li><a href="#">修改邮箱</a></li>
                    </ul>
                </li>

                <li class="nav-group post-manage"><a href="#">帖子管理</a></li>
                <li class="comments-manage"><a href="#">评论管理</a></li>
                <li class="board-manage"><a href="#">板块管理</a></li>

                <li class="nav-group user-manage"><a href="#">用户管理</a></li>
                <li class="role-manage"><a href="#">组管理</a></li>

                <li class="nav-group cmsuser-manage"><a href="#">CMS用户管理</a></li>
                <li class="cmsrole-manage"><a href="#">CMS组管理</a></li>
            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>标题</h1>
            <div class="main_content">
                整体内容
            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/cms_login.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
{#    <link rel="icon" href="../../favicon.ico">#}

    <title>登录论坛(sign for bbs)</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
{#    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">#}

    <!-- Custom styles for this template -->
{#    <link href="signin.css" rel="stylesheet">#}
      <link href="{{ url_for('static',filename='cms/css/signin.css') }}" rel="stylesheet">

{#    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->#}
{#    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->#}
{#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}
{##}
{#    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->#}
{#    <!--[if lt IE 9]>#}
{#      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>#}
{#      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>#}
{#    <![endif]-->#}
  </head>

  <body>

    <div class="container">

      <form class="form-signin"  method= "post">
        <h2 class="form-signin-heading">请登录</h2>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="inputEmail" class="sr-only">邮箱(Email address):</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="邮箱(Email address)" name="email" required autofocus>
{#          这里添加了三个name#}
        <label for="inputPassword" class="sr-only">密码(Password):</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="密码(Password)" name="password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="1" name="remember"> 记住我(Remember me)
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录:(Sign in)</button>
      </form>

{#这里是添加的#}
        {% if message %}
        <p style="text-align: center" class="text-danger">{{ message }}</p>
        {% endif %}

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
{#    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>#}
  </body>
</html>

templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}

{% block title %}帖子管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是帖子管理页面
{% endblock %}

templates/cms/cms_profile.html
{% extends 'cms/cms_base.html'%}
{% block title %}
    个人信息
{% endblock %}

{% block page_title %}
{{ self.title() }}
{% endblock %}


{% block main_content %}
    {% set user = g.cms_user  %}
<table class="table table-bordered">
<tbody>

<tr>
    <td>用户名:</td>
        <td>{{  user.username }}</td>


</tr>
<tr>
    <td>邮箱:</td>
        <td>{{  user.email }}</td>


</tr>
<tr>
    <td>角色</td>
        <td>

                    {% for role in user.roles %}
                        {{ role.name }}
                        {% if not loop.last %}，{% endif %}
                    {% endfor %}


        </td>


</tr>
<tr>
    <td>权限</td>
        <td>
                    {% for role in user.roles %}
                        {{ role.desc }}
                        {% if not loop.last %}/{% endif %}
                    {% endfor %}

        </td>


</tr>
<tr>
    <td>加入时间</td>
        <td>{{  user.join_time}}</td>


</tr>
</tbody>

</table>
{% endblock %}

templates/cms/cms_resetemail.html
{% extends "cms/cms_base.html" %}
{% from "common/_macros.html" import static %}

{% block title -%}
    修改邮箱
{%- endblock %}

{% block head %}
{#     <style>#}
{#        .form-container{#}
{#            width: 300px;#}
{#        }#}
{#    </style>#}
{#    这里样式不写是因为这里继承了cms_base.html,而cms_base.html又引用了base.css#}
    <script src="{{ static('cms/js/resetemail.js') }}"></script>
{% endblock %}

{% block page_title -%}
    {{ self.title() }}
{%- endblock %}

{% block main_content %}
    <form action="" method="post">
        <div class="form-container">
            <div class="form-group">
                <div class="input-group">
                    <input type="email" class="form-control" name="email" placeholder="新邮箱">
                    <span class="input-group-addon" id="captcha-btn"  style="cursor: pointer">获取验证码</span>
{#                    id="captcha-btn" style="cursor:pointer;"#}
                </div>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="captcha" placeholder="邮箱验证码">
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="submit">立即修改</button>
            </div>
        </div>
    </form>
{% endblock %}